name: First-Workflow
on: [push]

jobs:
  job-1-run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: "Step: Echo a String"
        run: echo "Hello World !......"
      - name: "Step: Multi-Line Commands"
        run: |
          node -v
          cat /etc/os-release
    
  job-2-parallel-macos:
    runs-on: macos-latest
    steps:
      - name: "Step: Check Software Version"
        run: |
          sw_vers